
export default new Map([
["content/writing/building-retry-and-dead-letter-queue-workflows.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Fbuilding-retry-and-dead-letter-queue-workflows.mdx&astroContentModuleFlag=true")],
["content/writing/diagnosing-race-conditions-in-event-driven-applications.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Fdiagnosing-race-conditions-in-event-driven-applications.mdx&astroContentModuleFlag=true")],
["content/writing/transactional-outbox-versus-dual-writes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Ftransactional-outbox-versus-dual-writes.mdx&astroContentModuleFlag=true")],
["content/writing/designing-idempotent-background-jobs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Fdesigning-idempotent-background-jobs.mdx&astroContentModuleFlag=true")],
["content/writing/what-i-learned-reducing-aws-infrastructure-costs.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Fwhat-i-learned-reducing-aws-infrastructure-costs.mdx&astroContentModuleFlag=true")],
["content/work/conose-ph.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwork%2Fconose-ph.mdx&astroContentModuleFlag=true")],
["content/writing/where-ai-assisted-coding-helps-and-where-it-does-not.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Fwhere-ai-assisted-coding-helps-and-where-it-does-not.mdx&astroContentModuleFlag=true")],
["content/work/ph-live-music.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwork%2Fph-live-music.mdx&astroContentModuleFlag=true")],
["content/work/exact-construct.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwork%2Fexact-construct.mdx&astroContentModuleFlag=true")],
["content/writing/safely-refactoring-a-production-typescript-application.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Fsafely-refactoring-a-production-typescript-application.mdx&astroContentModuleFlag=true")],
["content/work/mdi-novare.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwork%2Fmdi-novare.mdx&astroContentModuleFlag=true")],
["content/work/viyahe-monark.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwork%2Fviyahe-monark.mdx&astroContentModuleFlag=true")],
["content/writing/race-condition-and-architecture-refactor.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=content%2Fwriting%2Frace-condition-and-architecture-refactor.mdx&astroContentModuleFlag=true")]]);
		