name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env: 
      PORT_PROD: 8082
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install dependencies (pnpm)
        if: steps.pnpm-cache.cache-hit != 'true'
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Build Astro App
        run: pnpm build 

  
  deploy: 
    runs-on: self-hosted 
    needs: [build]
    env: 
      PROJECT_DIR: /var/www/axlc.me
    steps: 
      - name: Copy files to /var/www/axlc.me
        run: |
          rm -rf $PROJECT_DIR/*
          cp -r ./ $PROJECT_DIR